# ===
# File Summary
# Path: backend\apps\relationships\migrations\0001_initial.py
# Type: python
# Purpose: Relationships domain for entity graph APIs and relationship operations.
# Primary responsibilities:
# - Domain behavior is summarized for fast onboarding and avoids full-file reread.
# - Core symbols: Migration
# Inputs:
# - Downstream and upstream interactions in the same domain.
# Outputs:
# - API payloads, records, side effects, or UI views depending on file role.
# Dependencies:
# - Shared runtime services and adjacent domain modules.
# Known risks:
# - Validate behavior after migrations, dependency upgrades, or contract changes.
# ===
# 

# Generated by Django 5.2.15 on 2026-06-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0002_recordobjecttypelock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type_key', models.CharField(max_length=120)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='records.record')),
                ('target_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='records.record')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['relationship_type_key'], name='relationshi_relatio_6dbc26_idx'), models.Index(fields=['source_record', 'relationship_type_key'], name='relationshi_source__440331_idx'), models.Index(fields=['target_record', 'relationship_type_key'], name='relationshi_target__448631_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_record', 'target_record', 'relationship_type_key'), name='unique_relationship_edge')],
            },
        ),
    ]

