# ===
# File Summary
# Path: backend\apps\config_registry\migrations\0001_initial.py
# Type: python
# Purpose: Configuration registry service for dynamic schemas, publishing, and config governance.
# Primary responsibilities:
# - Domain behavior is summarized for fast onboarding and avoids full-file reread.
# - Core symbols: Migration
# Inputs:
# - Downstream and upstream interactions in the same domain.
# Outputs:
# - API payloads, records, side effects, or UI views depending on file role.
# Dependencies:
# - Shared runtime services and adjacent domain modules.
# Known risks:
# - Validate behavior after migrations, dependency upgrades, or contract changes.
# ===
# 

# Generated by Django 5.2.15 on 2026-06-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField(unique=True)),
                ("data", models.JSONField(default=dict)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_versions_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurationDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_drafts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_drafts",
                        to="config_registry.configurationversion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuration_drafts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DashboardDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("payload", models.JSONField(default=dict)),
                (
                    "configuration_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_definitions",
                        to="config_registry.configurationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["configuration_version", "key"],
            },
        ),
        migrations.CreateModel(
            name="FolderTemplateDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("payload", models.JSONField(default=dict)),
                (
                    "configuration_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_template_definitions",
                        to="config_registry.configurationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["configuration_version", "key"],
            },
        ),
        migrations.CreateModel(
            name="FormLayoutDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("payload", models.JSONField(default=dict)),
                (
                    "configuration_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_layout_definitions",
                        to="config_registry.configurationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["configuration_version", "key"],
            },
        ),
        migrations.CreateModel(
            name="ObjectTypeDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120)),
                ("label", models.CharField(max_length=200)),
                ("plural_label", models.CharField(blank=True, max_length=200)),
                ("payload", models.JSONField(default=dict)),
                (
                    "configuration_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_type_definitions",
                        to="config_registry.configurationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["configuration_version", "key"],
            },
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=120)),
                ("label", models.CharField(max_length=200)),
                ("field_type", models.CharField(max_length=40)),
                ("required", models.BooleanField(default=False)),
                ("payload", models.JSONField(default=dict)),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="config_registry.objecttypedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["object_type", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="objecttypedefinition",
            constraint=models.UniqueConstraint(
                fields=("configuration_version", "key"), name="unique_object_type_per_config_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="formlayoutdefinition",
            constraint=models.UniqueConstraint(
                fields=("configuration_version", "key"), name="unique_form_layout_per_config_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="foldertemplatedefinition",
            constraint=models.UniqueConstraint(
                fields=("configuration_version", "key"), name="unique_folder_template_per_config_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="fielddefinition",
            constraint=models.UniqueConstraint(
                fields=("object_type", "key"), name="unique_field_per_object_type_definition"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboarddefinition",
            constraint=models.UniqueConstraint(
                fields=("configuration_version", "key"), name="unique_dashboard_per_config_version"
            ),
        ),
    ]

