# Generated by Django 5.2.15 on 2026-06-06

from django.db import migrations, models
from django.db.models import Max


def seed_configuration_sequence(apps, schema_editor):
    ConfigurationSequence = apps.get_model("config_registry", "ConfigurationSequence")
    ConfigurationVersion = apps.get_model("config_registry", "ConfigurationVersion")
    max_version = ConfigurationVersion.objects.aggregate(max_version=Max("version"))["max_version"] or 0
    ConfigurationSequence.objects.update_or_create(
        pk=1,
        defaults={"next_version": max_version + 1},
    )


def remove_configuration_sequence(apps, schema_editor):
    ConfigurationSequence = apps.get_model("config_registry", "ConfigurationSequence")
    ConfigurationSequence.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("config_registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationSequence",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("next_version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "configuration sequence",
                "verbose_name_plural": "configuration sequence",
            },
        ),
        migrations.RunPython(seed_configuration_sequence, remove_configuration_sequence),
    ]
