# ===
# File Summary
# Path: backend\apps\accounts\migrations\0003_recordpermission.py
# Type: python
# Purpose: Accounts service handling identity, roles, permissions, and authentication-facing APIs.
# Primary responsibilities:
# - Domain behavior is summarized for fast onboarding and avoids full-file reread.
# - Core symbols: Migration
# Inputs:
# - Downstream and upstream interactions in the same domain.
# Outputs:
# - API payloads, records, side effects, or UI views depending on file role.
# Dependencies:
# - Shared runtime services and adjacent domain modules.
# Known risks:
# - Validate behavior after migrations, dependency upgrades, or contract changes.
# ===
# 

# Generated by Django 5.2.15 on 2026-06-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_seed_role_groups"),
        ("records", "0002_recordobjecttypelock"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=120)),
                ("object_type_key", models.CharField(max_length=120)),
                ("can_view", models.BooleanField(default=True)),
                ("can_create", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_release", models.BooleanField(default=False)),
                ("can_admin", models.BooleanField(default=False)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_permissions",
                        to="records.record",
                    ),
                ),
            ],
            options={
                "ordering": ["object_type_key", "record_id", "role_name"],
                "indexes": [
                    models.Index(
                        fields=["object_type_key", "record"],
                        name="accounts_re_object__438915_idx",
                    ),
                    models.Index(
                        fields=["role_name", "object_type_key"],
                        name="accounts_re_role_na_979001_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recordpermission",
            constraint=models.UniqueConstraint(
                fields=("role_name", "record"),
                name="unique_role_record_permission",
            ),
        ),
    ]

