# ===
# File Summary
# Path: backend\apps\records\migrations\0001_initial.py
# Type: python
# Purpose: Records domain for core traceability records, validation, and coding constraints.
# Primary responsibilities:
# - Domain behavior is summarized for fast onboarding and avoids full-file reread.
# - Core symbols: Migration
# Inputs:
# - Downstream and upstream interactions in the same domain.
# Outputs:
# - API payloads, records, side effects, or UI views depending on file role.
# Dependencies:
# - Shared runtime services and adjacent domain modules.
# Known risks:
# - Validate behavior after migrations, dependency upgrades, or contract changes.
# ===
# 

# Generated by Django 5.2.15 on 2026-06-06 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type_key', models.CharField(max_length=120)),
                ('code_pattern', models.CharField(max_length=200)),
                ('year_scope', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['object_type_key'], name='records_cod_object__c8bbb9_idx'), models.Index(fields=['code_pattern'], name='records_cod_code_pa_7fabe0_idx')],
                'constraints': [models.UniqueConstraint(fields=('object_type_key', 'code_pattern', 'year_scope'), name='unique_code_sequence_scope', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type_key', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released')], default='draft', max_length=24)),
                ('schema_version', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['object_type_key'], name='records_rec_object__133691_idx'), models.Index(fields=['code'], name='records_rec_code_18c0d9_idx'), models.Index(fields=['status'], name='records_rec_status_4b157d_idx')],
            },
        ),
    ]

