# ===
# File Summary
# Path: backend\apps\documents\migrations\0001_initial.py
# Type: python
# Purpose: Document domain service managing records, revisions, and extraction workflows.
# Primary responsibilities:
# - Domain behavior is summarized for fast onboarding and avoids full-file reread.
# - Core symbols: Migration
# Inputs:
# - Downstream and upstream interactions in the same domain.
# Outputs:
# - API payloads, records, side effects, or UI views depending on file role.
# Dependencies:
# - Shared runtime services and adjacent domain modules.
# Known risks:
# - Validate behavior after migrations, dependency upgrades, or contract changes.
# ===
# 

# Generated by Django 5.2.15 on 2026-06-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0002_alter_folderchangeevent_event_type'),
        ('records', '0002_recordobjecttypelock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='folders.managedfolder')),
                ('owner_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.record')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_label', models.CharField(max_length=80)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('unsupported', 'Unsupported'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released')], default='draft', max_length=24)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'revision_label', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.document')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='documents.documentrevision')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentrevision'),
        ),
        migrations.AddIndex(
            model_name='documentrevision',
            index=models.Index(fields=['document', 'state'], name='documents_d_documen_f1726d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrevision',
            index=models.Index(fields=['sha256'], name='documents_d_sha256_25caf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'revision_label'), name='unique_revision_label_per_document'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['document', 'action'], name='documents_d_documen_dc0613_idx'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['timestamp'], name='documents_d_timesta_67b5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner_record', 'document_type'], name='documents_d_owner_r_be0012_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['state'], name='documents_d_state_df10a5_idx'),
        ),
    ]

