# Generated by Django 5.2.15 on 2026-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_id', models.CharField(max_length=120, unique=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('database_dump_path', models.TextField(blank=True, default='')),
                ('managed_files_archive_path', models.TextField(blank=True, default='')),
                ('media_archive_path', models.TextField(blank=True, default='')),
                ('config_export_path', models.TextField(blank=True, default='')),
                ('audit_export_path', models.TextField(blank=True, default='')),
                ('sha256_manifest', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=24)),
                ('failure_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['backup_id'], name='backups_manifest_id_idx'), models.Index(fields=['state', 'started_at'], name='backups_manifest_state_idx')],
            },
        ),
    ]
