# Generated by Django 5.2.15 on 2026-06-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("filters", models.JSONField(blank=True, default=list)),
                ("columns", models.JSONField(blank=True, default=list)),
                ("sort", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(fields=["owner", "name"], name="reports_sav_owner_i_9c9796_idx"),
                    models.Index(fields=["created_at"], name="reports_sav_created_03dc5f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("count_by_status", "Count by status"),
                            ("count_by_object_type", "Count by object type"),
                            ("overdue_project_tasks", "Overdue project tasks"),
                            ("missing_required_documents", "Missing required documents"),
                            ("recent_changes", "Recent changes"),
                            ("workflow_bottlenecks", "Workflow bottlenecks"),
                        ],
                        max_length=80,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="reports.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(fields=["dashboard", "sort_order"], name="reports_das_dashboa_ca4e1c_idx"),
                    models.Index(fields=["widget_type"], name="reports_das_widget__103de8_idx"),
                ],
            },
        ),
    ]
