# Generated by Django 5.2.15 on 2026-06-06 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0002_recordobjecttypelock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_role', models.CharField(default='primary', max_length=80)),
                ('absolute_path', models.TextField()),
                ('relative_path', models.TextField(unique=True)),
                ('template_key', models.CharField(max_length=120)),
                ('state', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=24)),
                ('last_scan_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_folders', to='records.record')),
            ],
            options={
                'ordering': ['record_id', 'folder_role'],
            },
        ),
        migrations.CreateModel(
            name='FolderFileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('file_hash', models.CharField(max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('modified_ns', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_snapshots', to='folders.managedfolder')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='FolderChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('moved', 'Moved'), ('collision', 'Collision'), ('link_requested', 'Link requested')], max_length=32)),
                ('path', models.TextField()),
                ('detected_hash', models.CharField(blank=True, default='', max_length=64)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ignored', 'Ignored'), ('linked', 'Linked')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_change_events', to='records.record')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_folder_events', to=settings.AUTH_USER_MODEL)),
                ('managed_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='folders.managedfolder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='managedfolder',
            index=models.Index(fields=['record', 'folder_role'], name='folders_man_record__a61572_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfolder',
            index=models.Index(fields=['state'], name='folders_man_state_d5f824_idx'),
        ),
        migrations.AddConstraint(
            model_name='managedfolder',
            constraint=models.UniqueConstraint(fields=('record', 'folder_role'), name='unique_managed_folder_role_per_record'),
        ),
        migrations.AddIndex(
            model_name='folderfilesnapshot',
            index=models.Index(fields=['managed_folder', 'path'], name='folders_fol_managed_b7200f_idx'),
        ),
        migrations.AddConstraint(
            model_name='folderfilesnapshot',
            constraint=models.UniqueConstraint(fields=('managed_folder', 'path'), name='unique_snapshot_path_per_managed_folder'),
        ),
        migrations.AddIndex(
            model_name='folderchangeevent',
            index=models.Index(fields=['review_status', 'event_type'], name='folders_fol_review__e5b790_idx'),
        ),
        migrations.AddIndex(
            model_name='folderchangeevent',
            index=models.Index(fields=['managed_folder', 'review_status'], name='folders_fol_managed_8aa1c2_idx'),
        ),
        migrations.AddIndex(
            model_name='folderchangeevent',
            index=models.Index(fields=['matched_record', 'review_status'], name='folders_fol_matched_2b76e5_idx'),
        ),
    ]
