# Generated by Django 5.2.15 on 2026-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderchangeevent',
            name='event_type',
            field=models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('moved', 'Moved'), ('collision', 'Collision'), ('link_requested', 'Link requested'), ('generation_failed', 'Generation failed')], max_length=32),
        ),
    ]
