# ===
# File Summary
# Path: backend\apps\folders\migrations\0002_alter_folderchangeevent_event_type.py
# Type: python
# Purpose: Folders domain handling templates, scans, change events, and review flows.
# Primary responsibilities:
# - Domain behavior is summarized for fast onboarding and avoids full-file reread.
# - Core symbols: Migration
# Inputs:
# - Downstream and upstream interactions in the same domain.
# Outputs:
# - API payloads, records, side effects, or UI views depending on file role.
# Dependencies:
# - Shared runtime services and adjacent domain modules.
# Known risks:
# - Validate behavior after migrations, dependency upgrades, or contract changes.
# ===
# 

# Generated by Django 5.2.15 on 2026-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderchangeevent',
            name='event_type',
            field=models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('moved', 'Moved'), ('collision', 'Collision'), ('link_requested', 'Link requested'), ('generation_failed', 'Generation failed')], max_length=32),
        ),
    ]

